- name: Install git
  apt:
    name: git
    state: latest
  become: yes
  become_user: root

- name: Install mpd
  apt:
    name: mpd
    state: latest
  become: yes
  become_user: root

- name: Install mpc
  apt:
    name: mpc
    state: latest
  become: yes
  become_user: root
